name: Test anoma-applib

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HelloWorld
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Download the Juvix binary
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: anoma/juvix
          cache: enable
      - name: Clean
        run: juvix clean --global && juvix dependencies update 
      - name: Type Check
        run: juvix typecheck
      - name: Format Check
        run: juvix format
